Add NetBox device image preview

diff --git a/printlabel b/printlabel
--- a/printlabel
+++ b/printlabel
@@ -59,6 +59,13 @@ supports_color() {
 }
 
 init_color_support() {
+  if [[ -n "${PRINTLABEL_FORCE_COLOR:-}" ]]
+  then
+    PRINTLABEL_COLOR_STDOUT=1
+    PRINTLABEL_COLOR_STDERR=1
+    return 0
+  fi
+
   if [[ -t 1 ]]
   then
     PRINTLABEL_COLOR_STDOUT=1
@@ -214,6 +221,17 @@ find_magick() {
   fi
 
   log_error "ImageMagick is required but neither 'magick' nor 'convert' was found."
+  return 1
+}
+
+find_curl() {
+  if command -v curl >/dev/null 2>&1
+  then
+    printf '%s\n' "curl"
+    return 0
+  fi
+
+  log_error "curl is required for NetBox image previews."
   return 1
 }
 
@@ -397,6 +415,11 @@ can_preview_with_kitty() {
   if ! command -v kitten >/dev/null 2>&1
   then
     return 1
+  fi
+
+  if [[ -n "${PRINTLABEL_FORCE_KITTY:-}" ]]
+  then
+    return 0
   fi
 
   if ! [[ -t 1 ]]
@@ -767,6 +790,11 @@ select_netbox_object() {
   local cache_file
   local candidates_file
   local selection_file
+  local preview_command
+  local preview_script
+  local preview_cache
+  local preview_netbox_url
+  local preview_netbox_token
   local -a fzf_args
 
   objects_json="$(
@@ -821,6 +849,11 @@ select_netbox_object() {
   candidates_file="$(mktemp printlabel-netbox-candidates.XXXXXX.tsv)"
   selection_file="$(mktemp printlabel-netbox-selection.XXXXXX.txt)"
   printf '%s\n' "${objects_json}" > "${cache_file}"
+  printf -v preview_script '%q' "${BASH_SOURCE[0]}"
+  printf -v preview_cache '%q' "${cache_file}"
+  printf -v preview_netbox_url '%q' "${netbox_url}"
+  printf -v preview_netbox_token '%q' "${netbox_token}"
+  preview_command="PRINTLABEL_FORCE_COLOR=1 PRINTLABEL_FORCE_KITTY=1 ${preview_script} __netbox-preview ${preview_cache} {1} {2} ${preview_netbox_url} ${preview_netbox_token}"
   fzf_args=(
     --ansi
     --delimiter=$'\t'
@@ -828,32 +861,7 @@ select_netbox_object() {
     --prompt='NetBox object> '
     --header='Select a device or rack to print'
     --preview-window='right:60%:wrap'
-    --preview "
-      ${jq_bin} -r --arg kind {1} --arg id {2} '
-        def color(code; text):
-          \"\u001b[\" + code + \"m\" + text + \"\u001b[0m\";
-        def spaces(count):
-          reduce range(0; count) as \$index (\"\"; . + \" \");
-        def field(field_name; label_code; value; value_code):
-          (field_name as \$label | color(label_code; (\$label + spaces(14 - (\$label | length))))) + \"  \" + color(value_code; value);
-
-        .[] |
-        select(.printlabel_kind == \$kind and (.id | tostring) == \$id) |
-        [
-          field(\"Type\"; \"1;36\"; (.printlabel_kind // \"\"); \"0;33\"),
-          field(\"ID\"; \"1;36\"; (.id | tostring); \"0;33\"),
-          field(\"Name\"; \"1;36\"; (.name // \"\"); \"0;32\"),
-          field(\"Asset tag\"; \"1;36\"; (.asset_tag // \"\"); \"0;33\"),
-          field(\"Serial\"; \"1;36\"; (.serial // \"\"); \"0;33\"),
-          field(\"Manufacturer\"; \"1;36\"; (.device_type.manufacturer.name // \"\"); \"0;32\"),
-          field(\"Device type\"; \"1;36\"; (.device_type.model // \"\"); \"0;32\"),
-          field(\"Role\"; \"1;36\"; (.role.name // \"\"); \"0;32\"),
-          field(\"Site\"; \"1;36\"; (.site.name // \"\"); \"0;32\"),
-          field(\"Location\"; \"1;36\"; (.location.name // \"\"); \"0;32\"),
-          field(\"URL\"; \"1;36\"; (.display_url // \"\"); \"0;34\")
-        ] | join(\"\\n\")
-      ' '${cache_file}'
-    "
+    --preview "${preview_command}"
   )
 
   if [[ -n "${netbox_query}" ]]
@@ -1082,6 +1090,258 @@ print_netbox_summary() {
   done <<< "${summary_lines}"
 }
 
+netbox_preview_summary_lines() {
+  local jq_bin="$1"
+  local netbox_object_json="$2"
+
+  "${jq_bin}" -r '
+    [
+      ["Type", .printlabel_kind // "unknown"],
+      ["ID", ((.id // "") | tostring)],
+      ["Name", (.name // "")],
+      ["Manufacturer", (.device_type.manufacturer.name // "")],
+      ["Device type", (.device_type.model // "")],
+      ["Asset tag", (.asset_tag // "")],
+      ["Serial", (.serial // "")],
+      ["Role", (.role.name // "")],
+      ["Site", (.site.name // "")],
+      ["Location", (.location.name // "")],
+      ["URL", (.display_url // "")]
+    ]
+    | .[]
+    | @tsv
+  ' <<< "${netbox_object_json}"
+}
+
+print_netbox_fzf_preview_summary() {
+  local jq_bin="$1"
+  local netbox_object_json="$2"
+  local summary_lines
+  local key
+  local value
+  local value_color
+  local width=14
+
+  summary_lines="$(netbox_preview_summary_lines "${jq_bin}" "${netbox_object_json}")" || return 1
+
+  while IFS=$'\t' read -r key value
+  do
+    if [[ -z "${value}" ]]
+    then
+      value="$(colorize_multi 'gray strikethrough' 'N/A' 1)"
+    else
+      value_color="$(netbox_value_color "${key}")"
+      value="$(colorize "${value_color}" "${value}" 1)"
+    fi
+
+    printf '%s  %s\n' \
+      "$(colorize_multi 'bold cyan' "$(printf '%-*s' "${width}" "${key}")" 1)" \
+      "${value}"
+  done <<< "${summary_lines}"
+}
+
+resolve_netbox_media_url() {
+  local base_url="$1"
+  local media_url="$2"
+
+  if [[ -z "${media_url}" ]]
+  then
+    return 0
+  fi
+
+  if [[ "${media_url}" =~ ^https?:// ]]
+  then
+    printf '%s\n' "${media_url}"
+    return 0
+  fi
+
+  if [[ -z "${base_url}" ]]
+  then
+    printf '%s\n' "${media_url}"
+    return 0
+  fi
+
+  if [[ "${media_url}" == /* ]]
+  then
+    printf '%s%s\n' "${base_url%/}" "${media_url}"
+    return 0
+  fi
+
+  printf '%s/%s\n' "${base_url%/}" "${media_url#./}"
+}
+
+fetch_netbox_device_type_json() {
+  local jq_bin="$1"
+  local netbox_object_json="$2"
+  local netbox_url="$3"
+  local netbox_token="$4"
+  local curl_bin
+  local device_type_url=""
+  local device_type_id=""
+  local resolved_device_type_url=""
+
+  device_type_url="$("${jq_bin}" -r '
+    .device_type.url? // ""
+  ' <<< "${netbox_object_json}")" || return 1
+  device_type_id="$("${jq_bin}" -r '
+    (.device_type.id? // "") | tostring
+  ' <<< "${netbox_object_json}")" || return 1
+
+  if [[ -n "${device_type_url}" && "${device_type_url}" != "null" ]]
+  then
+    resolved_device_type_url="$(resolve_netbox_media_url "${netbox_url}" "${device_type_url}")"
+  elif [[ -n "${device_type_id}" && "${device_type_id}" != "null" && -n "${netbox_url}" ]]
+  then
+    resolved_device_type_url="${netbox_url%/}/api/dcim/device-types/${device_type_id}/"
+  else
+    return 1
+  fi
+
+  curl_bin="$(find_curl)" || return 1
+
+  if [[ -n "${netbox_token}" ]]
+  then
+    "${curl_bin}" -fsSL \
+      -H "Authorization: Token ${netbox_token}" \
+      "${resolved_device_type_url}"
+    return $?
+  fi
+
+  "${curl_bin}" -fsSL "${resolved_device_type_url}"
+}
+
+extract_netbox_front_image_url() {
+  local jq_bin="$1"
+  local json_input="$2"
+
+  "${jq_bin}" -r '
+    [
+      .front_image.url?,
+      .front_image?,
+      .front_image_url?,
+      .device_type.front_image.url?,
+      .device_type.front_image?,
+      .device_type.front_image_url?,
+      .image_front.url?,
+      .image_front?,
+      .device_type.image_front.url?,
+      .device_type.image_front?
+    ]
+    | map(select(type == "string" and length > 0 and . != "null"))
+    | first // ""
+  ' <<< "${json_input}"
+}
+
+print_netbox_fzf_preview_image() {
+  local jq_bin="$1"
+  local netbox_object_json="$2"
+  local netbox_url="$3"
+  local netbox_token="$4"
+  local curl_bin
+  local image_tool
+  local image_url=""
+  local resolved_image_url
+  local device_type_json=""
+  local tmp_dir
+  local source_image
+  local preview_image
+
+  if ! can_preview_with_kitty
+  then
+    return 1
+  fi
+
+  curl_bin="$(find_curl)" || return 1
+  image_url="$(extract_netbox_front_image_url "${jq_bin}" "${netbox_object_json}")" || return 1
+
+  if [[ -z "${image_url}" ]]
+  then
+    device_type_json="$(
+      fetch_netbox_device_type_json "${jq_bin}" "${netbox_object_json}" "${netbox_url}" "${netbox_token}"
+    )" || return 1
+    image_url="$(extract_netbox_front_image_url "${jq_bin}" "${device_type_json}")" || return 1
+  fi
+
+  if [[ -z "${image_url}" ]]
+  then
+    return 1
+  fi
+
+  resolved_image_url="$(resolve_netbox_media_url "${netbox_url}" "${image_url}")"
+  tmp_dir="$(mktemp -d printlabel-netbox-preview.XXXXXX)" || return 1
+  source_image="${tmp_dir}/source-image"
+  preview_image="${tmp_dir}/preview-image.png"
+
+  if [[ -n "${netbox_token}" ]]
+  then
+    "${curl_bin}" -fsSL \
+      -H "Authorization: Token ${netbox_token}" \
+      "${resolved_image_url}" \
+      -o "${source_image}" || {
+      rm -rf "${tmp_dir}"
+      return 1
+    }
+  else
+    "${curl_bin}" -fsSL "${resolved_image_url}" -o "${source_image}" || {
+      rm -rf "${tmp_dir}"
+      return 1
+    }
+  fi
+
+  if image_tool="$(find_magick 2>/dev/null)"
+  then
+    "${image_tool}" "${source_image}" -resize 300x "${preview_image}" >/dev/null 2>&1 || {
+      rm -rf "${tmp_dir}"
+      return 1
+    }
+  else
+    cp "${source_image}" "${preview_image}" || {
+      rm -rf "${tmp_dir}"
+      return 1
+    }
+  fi
+
+  kitten icat --clear >/dev/null 2>&1 || true
+  kitten icat \
+    --stdin=no \
+    --transfer-mode=stream \
+    --align=left \
+    --no-trailing-newline \
+    "${preview_image}" || {
+    rm -rf "${tmp_dir}"
+    return 1
+  }
+  printf '\n\n'
+  rm -rf "${tmp_dir}"
+}
+
+print_netbox_fzf_preview() {
+  local cache_file="$1"
+  local selected_kind="$2"
+  local selected_id="$3"
+  local netbox_url="$4"
+  local netbox_token="$5"
+  local jq_bin
+  local netbox_object_json
+
+  jq_bin="$(find_jq)" || return 1
+  netbox_object_json="$(
+    # shellcheck disable=SC2016
+    "${jq_bin}" -c --arg kind "${selected_kind}" --arg id "${selected_id}" '
+      .[] | select(.printlabel_kind == $kind and (.id | tostring) == $id)
+    ' "${cache_file}"
+  )" || return 1
+
+  if [[ -z "${netbox_object_json}" ]]
+  then
+    return 1
+  fi
+
+  print_netbox_fzf_preview_summary "${jq_bin}" "${netbox_object_json}"
+  printf '\n'
+  print_netbox_fzf_preview_image "${jq_bin}" "${netbox_object_json}" "${netbox_url}" "${netbox_token}" || true
+}
+
 preview_label() {
   local preview_mode="${1:-}"
 
@@ -1152,6 +1412,13 @@ main() {
 
   script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
   init_color_support
+
+  if [[ "${1:-}" == "__netbox-preview" ]]
+  then
+    shift
+    print_netbox_fzf_preview "$@"
+    return $?
+  fi
 
   while [[ -n "${1:-}" ]]
   do
